<?php
/**
 * @var string $pathAssets
 * @var string $docs
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Simplon Docs Skeleton</title>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

    <link rel="stylesheet" href="<?php echo $pathAssets ?>/vendor/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo $pathAssets ?>/vendor/highlightjs/styles/github.css">
    <link rel="stylesheet" href="<?php echo $pathAssets ?>/eva/css/master.css">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,400,300,600,700" rel="stylesheet" type="text/css">
    <style type="text/css">
        body
        {
            margin: 10px 20px;
        }

        .doc-title
        {
            color: #369;
            border: 0;
            margin-bottom: 70px;
        }

        .content-title
        {
            border: 0;
        }

        .topic-title
        {
            border-bottom: 1px solid #eee;
            margin: 80px 0 30px;
        }

        .section-title
        {
            border-left: 15px solid #cef;
            background: #fafafa;
            border-radius: 4px;
            padding: 5px 10px;
            cursor: pointer;
        }

        table
        {
            background: #fff;
        }
    </style>
</head>
<body>

    <div class="container-fluid">
        <?php echo $docs ?>
    </div>

    <script src="<?php echo $pathAssets ?>/vendor/jquery/dist/jquery.min.js"></script>
    <script src="<?php echo $pathAssets ?>/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="<?php echo $pathAssets ?>/vendor/highlightjs/highlight.pack.js"></script>

    <script>
        $(function ()
        {
            var cacheKey = 'openSections';

            var updateCache = function (cache)
            {
                localStorage.setItem(cacheKey, JSON.stringify(cache));
            };

            // read cached open sections
            var openSections = JSON.parse(localStorage.getItem(cacheKey));

            if (openSections === null)
            {
                openSections = [];
            }

            $(".section-title").click(function ()
            {
                $(this).next().next().toggle();

                // is elm in cache
                var cacheIndex = openSections.indexOf(this.id)

                // cache section
                if (cacheIndex === -1)
                {
                    openSections.push(this.id);
                }
                else
                {
                    // remove cache
                    openSections.splice(cacheIndex, 1);
                }

                // save cache
                updateCache(openSections);
            });

            // trigger cached items
            openSections.forEach(function (elm)
            {
                $('#' + elm).next().next().toggle();
            });
        });
    </script>

    <script>hljs.initHighlightingOnLoad();</script>
</body>
</html>
